import Testing
@testable import OpenIslandCore

@Suite("Clipboard privacy filter")
struct ClipboardPrivacyTests {
    @Test("An ordinary copy from an ordinary app is never skipped")
    func ordinaryCopyIsNotSkipped() {
        #expect(!ClipboardPrivacy.shouldSkip(
            types: ["public.utf8-plain-text"],
            frontmostBundleID: "com.apple.Terminal",
            isLocked: false
        ))
    }

    @Test("A concealed-type copy is always skipped")
    func concealedTypeIsSkipped() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            frontmostBundleID: "com.apple.Terminal",
            isLocked: false
        ))
    }

    @Test("A transient-type copy is always skipped")
    func transientTypeIsSkipped() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: ["org.nspasteboard.TransientType"],
            frontmostBundleID: nil,
            isLocked: false
        ))
    }

    @Test("An auto-generated-type copy is always skipped")
    func autoGeneratedTypeIsSkipped() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: ["org.nspasteboard.AutoGeneratedType"],
            frontmostBundleID: nil,
            isLocked: false
        ))
    }

    @Test("A copy from a denied bundle identifier is skipped even without a UTI hint")
    func denyListBundleIsSkipped() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: ["public.utf8-plain-text"],
            frontmostBundleID: "com.1password.1password",
            isLocked: false
        ))
    }

    @Test("The default deny list covers every named password manager")
    func defaultDenyListCoversNamedManagers() {
        for bundleID in ClipboardPrivacy.defaultDenyList {
            #expect(ClipboardPrivacy.shouldSkip(
                types: [],
                frontmostBundleID: bundleID,
                isLocked: false
            ))
        }
    }

    @Test("A bundle identifier not on the deny list is not skipped on that basis alone")
    func unlistedBundleIsNotSkipped() {
        #expect(!ClipboardPrivacy.shouldSkip(
            types: ["public.utf8-plain-text"],
            frontmostBundleID: "com.example.notepad",
            isLocked: false
        ))
    }

    @Test("Nothing is recorded while the screen is locked, regardless of type or app")
    func lockedScreenSkipsEverything() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: ["public.utf8-plain-text"],
            frontmostBundleID: "com.apple.Terminal",
            isLocked: true
        ))
    }

    @Test("A custom deny list is honoured instead of the default")
    func customDenyListIsHonoured() {
        #expect(ClipboardPrivacy.shouldSkip(
            types: [],
            frontmostBundleID: "com.example.custom",
            isLocked: false,
            denyList: ["com.example.custom"]
        ))
        // The default list's own entries no longer apply once a custom list
        // is supplied.
        #expect(!ClipboardPrivacy.shouldSkip(
            types: [],
            frontmostBundleID: "com.1password.1password",
            isLocked: false,
            denyList: ["com.example.custom"]
        ))
    }
}
